dataset_path: C:\Users\NXTWAVE\Downloads\Rural Water Infrastructure Maintenance Cost
  Prediction System\mi_census5_13-14_Table6.6.csv
feature_columns:
- State
- District
- Block_Tehsil
- Village
- No_of_Surface_lift_Schemes_according_to_the_annual_cost_of_maintenance___Upto_Rs_1000
- No_of_Surface_lift_Schemes_according_to_the_annual_cost_of_maintenance___Rs1000_to_10000
- No_of_Surface_lift_Schemes_according_to_the_annual_cost_of_maintenance___Rs10000_to_50000
- No_of_Surface_lift_Schemes_according_to_the_annual_cost_of_maintenance___Rs50000_to_100000
- No_of_Surface_lift_Schemes_according_to_the_annual_cost_of_maintenance___More_than_Rs_100000
- total_schemes
- maintenance_score
- high_cost_schemes
- high_cost_ratio
models_used:
- Random Forest Regressor
- Gradient Boosting Regressor
- Deep Learning Neural Network
output_directory: C:\Users\NXTWAVE\Downloads\Rural Water Infrastructure Maintenance
  Cost Prediction System
project_name: Rural Water Infrastructure Maintenance Cost Prediction System
saved_files:
  accuracy_graph: C:\Users\NXTWAVE\Downloads\Rural Water Infrastructure Maintenance
    Cost Prediction System\rural_water_accuracy_graph.png
  comparison_graph: C:\Users\NXTWAVE\Downloads\Rural Water Infrastructure Maintenance
    Cost Prediction System\rural_water_comparison_graph.png
  encoders: C:\Users\NXTWAVE\Downloads\Rural Water Infrastructure Maintenance Cost
    Prediction System\rural_water_label_encoders.pkl
  h5_model: C:\Users\NXTWAVE\Downloads\Rural Water Infrastructure Maintenance Cost
    Prediction System\rural_water_model.h5
  heatmap: C:\Users\NXTWAVE\Downloads\Rural Water Infrastructure Maintenance Cost
    Prediction System\rural_water_heatmap.png
  pkl_model: C:\Users\NXTWAVE\Downloads\Rural Water Infrastructure Maintenance Cost
    Prediction System\rural_water_random_forest_model.pkl
  prediction_csv: C:\Users\NXTWAVE\Downloads\Rural Water Infrastructure Maintenance
    Cost Prediction System\rural_water_prediction.csv
  prediction_graph: C:\Users\NXTWAVE\Downloads\Rural Water Infrastructure Maintenance
    Cost Prediction System\rural_water_prediction_graph.png
  result_csv: C:\Users\NXTWAVE\Downloads\Rural Water Infrastructure Maintenance Cost
    Prediction System\rural_water_result.csv
  result_graph: C:\Users\NXTWAVE\Downloads\Rural Water Infrastructure Maintenance
    Cost Prediction System\rural_water_result_graph.png
  scaler: C:\Users\NXTWAVE\Downloads\Rural Water Infrastructure Maintenance Cost Prediction
    System\rural_water_scaler.pkl
target_column: maintenance_risk_score
