algorithm: SSA
all_features:
- State
- District
- Block_Tehsil
- Village
- No_of_Surface_lift_Schemes_according_to_the_annual_cost_of_maintenance___Upto_Rs_1000
- No_of_Surface_lift_Schemes_according_to_the_annual_cost_of_maintenance___Rs1000_to_10000
- No_of_Surface_lift_Schemes_according_to_the_annual_cost_of_maintenance___Rs10000_to_50000
- No_of_Surface_lift_Schemes_according_to_the_annual_cost_of_maintenance___Rs50000_to_100000
- No_of_Surface_lift_Schemes_according_to_the_annual_cost_of_maintenance___More_than_Rs_100000
- total_schemes
- maintenance_score
- high_cost_schemes
- high_cost_ratio
dataset_path: C:\Users\NXTWAVE\Downloads\Rural Water Infrastructure Maintenance Cost
  Prediction System\mi_census5_13-14_Table6.6.csv
files:
  accuracy_graph: C:\Users\NXTWAVE\Downloads\Rural Water Infrastructure Maintenance
    Cost Prediction System\ssa_accuracy_graph.png
  comparison_graph: C:\Users\NXTWAVE\Downloads\Rural Water Infrastructure Maintenance
    Cost Prediction System\ssa_comparison_graph.png
  feature_importance_graph: C:\Users\NXTWAVE\Downloads\Rural Water Infrastructure
    Maintenance Cost Prediction System\ssa_feature_importance_graph.png
  h5_model: C:\Users\NXTWAVE\Downloads\Rural Water Infrastructure Maintenance Cost
    Prediction System\ssa_model.h5
  heatmap: C:\Users\NXTWAVE\Downloads\Rural Water Infrastructure Maintenance Cost
    Prediction System\ssa_heatmap.png
  pkl_model: C:\Users\NXTWAVE\Downloads\Rural Water Infrastructure Maintenance Cost
    Prediction System\ssa_model.pkl
  prediction_csv: C:\Users\NXTWAVE\Downloads\Rural Water Infrastructure Maintenance
    Cost Prediction System\ssa_prediction.csv
  prediction_graph: C:\Users\NXTWAVE\Downloads\Rural Water Infrastructure Maintenance
    Cost Prediction System\ssa_prediction_graph.png
  result_csv: C:\Users\NXTWAVE\Downloads\Rural Water Infrastructure Maintenance Cost
    Prediction System\ssa_result.csv
  result_graph: C:\Users\NXTWAVE\Downloads\Rural Water Infrastructure Maintenance
    Cost Prediction System\ssa_result_graph.png
  ssa_progress_graph: C:\Users\NXTWAVE\Downloads\Rural Water Infrastructure Maintenance
    Cost Prediction System\ssa_ssa_progress_graph.png
  training_loss_graph: C:\Users\NXTWAVE\Downloads\Rural Water Infrastructure Maintenance
    Cost Prediction System\ssa_training_loss_graph.png
models_used:
- SSA + Random Forest
- SSA + Deep Learning
output_directory: C:\Users\NXTWAVE\Downloads\Rural Water Infrastructure Maintenance
  Cost Prediction System
project_name: Rural Water Infrastructure Maintenance Cost Prediction System
selected_features:
- State
- District
- Village
- No_of_Surface_lift_Schemes_according_to_the_annual_cost_of_maintenance___Rs10000_to_50000
- No_of_Surface_lift_Schemes_according_to_the_annual_cost_of_maintenance___More_than_Rs_100000
- maintenance_score
- high_cost_ratio
target_column: maintenance_risk_score
